### ISSUE TITLE
[DND5e] No emphasis roll option when attacking from the chat

### ISSUE THREAD

**Issue by Potato-Tyrant** [TPNils/emphasis-roll#1]
Foundry v12.327
DND5e 3.3.1

Whenever I select from the sheet a skill/saving throw, it correctly prompts me with the Advantage/Normal/Disadvantage/Emphasis roll choice, as posted in the module page.
But when I click on a weapon/spell, it sends in in the chat. When i select Attack from there, no Emphasis option appears in the roll mode choice.

Please see attachment

https://github.com/user-attachments/assets/3b419895-4398-4aa2-8246-815f24fc717f

**Comment by TPNils** [comment]
Currently it is/was on purpose to not show on attack rolls as it was not mentioned in the original document, but if you want it, I don't see why not. I will probably add is as a configuration option

**Comment by TPNils** [comment]
The option has been added to the latest release, which is now also available!

![image](https://github.com/user-attachments/assets/e6550315-babc-4f98-b8d1-eff2fadab841)
